# vi:ft=ruby:
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'universal-ctags/universal-ctags'
tap 'caskroom/cask'

brew 'ruby-build'
brew 'tmux'
brew 'ncdu'
brew 'reattach-to-user-namespace'
# brew 'vim'
brew 'macvim'
brew 'zsh'
brew 'fzf'
# brew 'neovim'
brew 'neovim/neovim/neovim'
brew 'gnu-sed'
brew 'ag'
brew 'universal-ctags', args: %w[HEAD]
# brew 'bash-completion'
brew 'openssl'
brew 'autojump'
# brew 'memcached'
brew 'node'
brew 'redis'
brew 'sqlite'
brew 'python'
brew 'wget'
brew 'curl'
brew 'gawk'
brew 'pcre'
brew 'go'
brew 'git'
brew 'hub'
brew 'nvm'
brew 'erlang'
brew 'elixir'
brew 'gnupg2'
brew 'gpg-agent'
brew 'graphviz'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'mongodb'
brew 'mariadb'
brew 'rabbitmq'
brew 'postgresql'
brew 'elasticsearch'
brew 'imagemagick'
brew 'leiningen'
# brew 'youtube-dl'
brew 'ffmpeg', args: %w[--with-libvpx --with-libvorbis]
brew 'heroku-toolbelt'
brew 'the_silver_searcher'

brew 'caskroom/cask/brew-cask'
cask 'dropbox'
cask 'evernote'
cask 'flux'
cash 'karabiner'
# cask 'dashlane'
cask '1password'
# cask 'spotify'
cask 'iterm2'
# cask 'slack'
cask 'alfred'
# cask 'charles'
cask 'skype'
cask 'opera'
cask 'skitch'
# cask 'google-chrome'
cask 'caffeine'
cask 'utorrent'
cask 'vlc'
cask 'cathode'
cask 'cyberduck'
# xcode
# tower
# thunderbird
# navicat
# kindle
# istat menu
# atom
# brackets
